### ISSUE TITLE
Error exporting GCODE with 1.8.1 : Job attributes are not ready

### ISSUE THREAD

**Issue by Nandox7** [barebaric/rayforge#300]
I can't generate gcode/export as independent of the iamge used it always fails in error.
This happens with the latest version 1.8.1, rollign back to 1.8.0 all works as expected.

Error seen in the log:
AttributeError: 'raygeo.ops.Ops' object has no attribute 'set_cut_speed'`

See attached logs, I'll add more details as I had to install 1.8.0 but i'll install again 1.8.1.

[rayforge_debug_2026-07-08_17-02-45.zip](https://github.com/user-attachments/files/29820951/rayforge_debug_2026-07-08_17-02-45.zip)

**Comment by knipknap** [comment]
Thanks for the detailed report, @Nandox7, and sorry about the trouble with G-code export.

I've looked into this, and I can explain what's happening. In version 1.8.1, Rayforge switched to a new geometry engine (raygeo) which renamed some internal methods — for example, what used to be called "set cut speed" is now called "set feed rate." All of Rayforge's own code was updated to use the new names, and the export works fine on its own.

The error you're seeing — specifically the one about `set_cut_speed` — means something outside of Rayforge's core code is still using the old name. The most common cause is a third-party addon (a plugin you may have installed) that hasn't been updated yet for the 1.8.1 changes. When that addon runs during the export step, it triggers the error, and that's what produces the "Job attributes are not ready" message you see in the log.

Could you try disabling any addons you have installed and then attempting the export again? If it works with addons disabled, that confirms which one needs an update.

If you're not using any addons, or if the issue persists after disabling them, let me know and I'll dig deeper — in that case I'd want to take a look at the debug log you attached to see exactly where the call is coming from.

Rolling back to 1.8.0 is a fine workaround in the meantime since the old geometry engine is still compatible with addons that haven't been migrated yet.

**Comment by knipknap** [comment]
I dug a little deeper and am more confused now. There is definitely a Rayforge/Raygeo version mismatch. How did you install Rayforge?

**Comment by knipknap** [comment]
I found maybe a potential cause that could lead to Windows builds using outdated Raygeo. Windows was not pinned to a particular Raygeo version - it used the latest version available. If for whatever reason at the time of the build the windows pypi repository delivered an old release (outdated caching?) then it would build using that.

I now updated the Windows build process to pin it to specific library versions. Starting 1.8.2, this should guarantee the correct library is used.

**Comment by Nandox7** [comment]
Apologies for the rather short report, I submitted it quite late and really needed to finish some works with the laser, so couldn't go back installing 1.8.1.

To answer to you previous questions and comments.
I'm running a rather stock install, using the installers for windows found at this github repo.
Also no addon used, only thing done was to configure my machine a Carvera Air, pretty stock stuff as you have it as part of the machines list.

**Comment by knipknap** [comment]
I just pushed release 1.8.2. The builds should be online in less than an hour.

**Comment by knipknap** [comment]
Thanks for reporting. Feel free to re-open if the issue persists.
